import { optionalNumberEnv } from "@/lib/env";

const DEFAULT_ACTIVE_POLL_SECONDS = 2;
const DEFAULT_IDLE_POLL_SECONDS = 10;

export const ACTIVE_POLL_SECONDS =
  optionalNumberEnv("DATAGEN_ACTIVE_POLL_SECONDS", DEFAULT_ACTIVE_POLL_SECONDS) ??
  DEFAULT_ACTIVE_POLL_SECONDS;

export const IDLE_POLL_SECONDS =
  optionalNumberEnv("DATAGEN_IDLE_POLL_SECONDS", DEFAULT_IDLE_POLL_SECONDS) ??
  DEFAULT_IDLE_POLL_SECONDS;
